# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KVJwOge-gZhB4h5D12v-hr8JMkjO5i5z

PAN Card Tampering Detection

This project can involve building a solution that integrates data preprocessing, anomaly detection techniques, and possibly machine learning models to effectively detect fraudulent activities related to PAN cards.
"""

#this project involves the use of computer vision
#import the necessary packages

from skimage.metrics import structural_similarity
import imutils
import cv2
from PIL import Image
import requests

from os import mkdir
!mkdir pan_card_tampering
!mkdir pan_card_tampering/image

#we can now open the images for display
original = Image.open(requests.get('https://editor.analyticsvidhya.com/uploads/29469original.png', stream=True).raw)
tampered = Image.open(requests.get('https://editor.analyticsvidhya.com/uploads/83117tampered.png', stream=True).raw)

#checking the format and sizes of the respective images
print("original image format: ", original.format)
print("tampered image format: ", tampered.format)

#Details of the image size in pixels given in a 2 tuple (height, width)
print("original image format: ", original.size)
print("tampered image format: ", tampered.size)
#remember checking the definite location of each image

#changing the size and the frmat is irrelevant since they are already saved

#display original
original

#display the tapered
tampered

original.save('pan_card_tampering/image/original.png')
tampered.save('pan_card_tampering/image/tampered.png')

original

tampered

#load the two inout images
original = cv2.imread('pan_card_tampering/image/original.png')
tampered = cv2.imread('pan_card_tampering/image/tampered.png')

#converting the images to grayscale
original_gray = cv2.cvtColor(original, cv2.COLOR_BGR2GRAY)
tampered_gray = cv2.cvtColor(tampered, cv2.COLOR_BGR2GRAY)

#compute and compare the structure similarities using SSMI{structure Similarity Index}
#it help us to determine the exat x,y coordinates the similarities of the 2 images are compared, the lower the ssim the lower the similarities


(score, diff) = structural_similarity(original_gray, tampered_gray, full=True)
diff = (diff * 255).astype("uint8")
print("SSIM: {}".format(score))

#calculating threshold values
thresh = cv2.threshold(diff, 0, 255, cv2.THRESH_BINARY_INV | cv2.THRESH_OTSU)[1]
cnts = cv2.findContours(thresh.copy(), cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_SIMPLE)
cnts = imutils.grab_contours(cnts)

#lets now loop the  contours
for c in cnts:
  #computing the bounding box of the contour and then drawing the bounding box on
  (x, y, w, h) = cv2.boundingRect(c)
  cv2.rectangle(original, (x, y), (x + w, y + h), (0, 0, 255), 2)
  cv2.rectangle(tampered, (x, y), (x + w, y + h), (0, 0, 255), 2)

# this is the display of the image countour (original)
print("Original Image")
Image.fromarray(original)

# dislay of the tampered image countour
print("Tampered Image")
Image.fromarray(tampered)

#display the differnce between the images with black
print("Different Images: ")
Image.fromarray(diff)

#Display the threshold between the 2 images
print("Threshold between the 2 images: ")
Image.fromarray(thresh)







